export const MultiCityFakeData = [
  {
    system: "Sabre",
    segment: "2",
    career: "UK",
    careerName: "Vistara",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 137077,
    Taxes: 12755,
    price: "140686",
    clientPrice: "149832",
    comission: "9146",
    pricebreakdown: [
      {
        BaseFare: "137077",
        Tax: "12755",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "11H 10Min",
      },
      {
        transit1: "2H 40Min",
      },
    ],
    bags: [
      {
        adultBag: "30KG",
      },
      {
        adultBag: "30KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "UK",
          marketingcareerName: "Vistara",
          marketingflight: "182",
          operatingcareer: "UK",
          operatingflight: "182",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T10:15:00",
          arrival: "DEL",
          arrivalTime: "2023-01-01T12:35:00",
          arrivalAirport: "Delhi Indira Gandhi Intl ",
          arrivalLocation: "Delhi , IN",
          flightduration: "2H 50Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "UK",
          marketingcareerName: "Vistara",
          marketingflight: "115",
          operatingcareer: "UK",
          operatingflight: "115",
          departure: "DEL",
          departureAirport: "Delhi Indira Gandhi Intl ",
          departureLocation: "Dhaka , IN",
          departureTime: "2023-01-01T23:45:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T08:10:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "5H 55Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
      [
        {
          marketingcareer: "UK",
          marketingcareerName: "Vistara",
          marketingflight: "106",
          operatingcareer: "UK",
          operatingflight: "106",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T10:30:00",
          arrival: "BOM",
          arrivalTime: "2023-02-01T13:45:00",
          arrivalAirport: "Chhatrapati Shivaji",
          arrivalLocation: "Mumbai , IN",
          flightduration: "5H 45Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "UK",
          marketingcareerName: "Vistara",
          marketingflight: "201",
          operatingcareer: "UK",
          operatingflight: "201",
          departure: "BOM",
          departureAirport: "Chhatrapati Shivaji",
          departureLocation: "Mumbai , IN",
          departureTime: "2023-02-01T16:25:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T18:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "3H 20Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-20 19:19",
    BasePrice: 174743,
    Taxes: 12367,
    price: "175439",
    clientPrice: "187110",
    comission: "11671",
    pricebreakdown: [
      {
        BaseFare: "174743",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "3H 0Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "30KG",
      },
      {
        adultBag: "30KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "315",
          operatingcareer: "BS",
          operatingflight: "315",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T10:30:00",
          arrival: "KUL",
          arrivalTime: "2023-01-01T16:25:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "3H 55Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "607",
          operatingcareer: "MH",
          operatingflight: "607",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-01T19:25:00",
          arrival: "SIN",
          arrivalTime: "2023-01-01T20:35:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-20 19:19",
    BasePrice: 174743,
    Taxes: 12367,
    price: "175439",
    clientPrice: "187110",
    comission: "11671",
    pricebreakdown: [
      {
        BaseFare: "174743",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "5H 50Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "30KG",
      },
      {
        adultBag: "30KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "317",
          operatingcareer: "BS",
          operatingflight: "317",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T20:05:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T02:00:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "3H 55Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "601",
          operatingcareer: "MH",
          operatingflight: "601",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T07:50:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T09:05:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 15Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-20 19:19",
    BasePrice: 174743,
    Taxes: 12367,
    price: "175439",
    clientPrice: "187110",
    comission: "11671",
    pricebreakdown: [
      {
        BaseFare: "174743",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "7H 10Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "30KG",
      },
      {
        adultBag: "30KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "317",
          operatingcareer: "BS",
          operatingflight: "317",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T20:05:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T02:00:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "3H 55Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "611",
          operatingcareer: "MH",
          operatingflight: "611",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T09:10:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T10:20:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "Y",
          seat: "9",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "Y",
          seat: "9",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "1",
    city: "2",
    career: "SQ",
    careerName: "Singapore Airlines",
    lastTicketTime: " ",
    BasePrice: 203717,
    Taxes: 13866,
    price: "203975",
    clientPrice: "217583",
    comission: "13608",
    pricebreakdown: [
      {
        BaseFare: "203717",
        Tax: "13866",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "0",
      },
      {
        transit1: "0",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "SQ",
          marketingcareerName: "Singapore Airlines",
          marketingflight: "447",
          operatingcareer: "SQ",
          operatingflight: "447",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T23:45:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T06:00:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "4H 15Min",
          bookingcode: "J",
          seat: "6",
        },
      ],
      [
        {
          marketingcareer: "SQ",
          marketingcareerName: "Singapore Airlines",
          marketingflight: "494",
          operatingcareer: "SQ",
          operatingflight: "494",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:05:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T18:45:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "7H 40Min",
          bookingcode: "",
          seat: "6",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "UL",
    careerName: "SriLankan Airlines",
    lastTicketTime: " ",
    BasePrice: 269757,
    Taxes: 12367,
    price: "264087",
    clientPrice: "282124",
    comission: "18037",
    pricebreakdown: [
      {
        BaseFare: "269757",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "4H 40Min",
      },
      {
        transit1: "1H 25Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "103",
          operatingcareer: "MH",
          operatingflight: "103",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T12:30:00",
          arrival: "KUL",
          arrivalTime: "2023-01-01T18:40:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "5",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "609",
          operatingcareer: "MH",
          operatingflight: "609",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-01T23:20:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T00:30:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "5",
        },
      ],
      [
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "303",
          operatingcareer: "UL",
          operatingflight: "303",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:50:00",
          arrival: "CMB",
          arrivalTime: "2023-02-01T17:10:00",
          arrivalAirport: "Bandaranaike Intl Airport",
          arrivalLocation: "Colombo , LK",
          flightduration: "3H 50Min",
          bookingcode: "J",
          seat: "5",
        },
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "225",
          operatingcareer: "UL",
          operatingflight: "225",
          departure: "CMB",
          departureAirport: "Bandaranaike Intl Airport",
          departureLocation: "Colombo , LK",
          departureTime: "2023-02-01T18:35:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T21:50:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "4H 45Min",
          bookingcode: "J",
          seat: "5",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "UL",
    careerName: "SriLankan Airlines",
    lastTicketTime: " ",
    BasePrice: 269757,
    Taxes: 12367,
    price: "264087",
    clientPrice: "282124",
    comission: "18037",
    pricebreakdown: [
      {
        BaseFare: "269757",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "2H 55Min",
      },
      {
        transit1: "1H 25Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "601",
          operatingcareer: "MH",
          operatingflight: "601",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T07:50:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T09:05:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 15Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "303",
          operatingcareer: "UL",
          operatingflight: "303",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:50:00",
          arrival: "CMB",
          arrivalTime: "2023-02-01T17:10:00",
          arrivalAirport: "Bandaranaike Intl Airport",
          arrivalLocation: "Colombo , LK",
          flightduration: "3H 50Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "225",
          operatingcareer: "UL",
          operatingflight: "225",
          departure: "CMB",
          departureAirport: "Bandaranaike Intl Airport",
          departureLocation: "Colombo , LK",
          departureTime: "2023-02-01T18:35:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T21:50:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "4H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "UL",
    careerName: "SriLankan Airlines",
    lastTicketTime: " ",
    BasePrice: 269757,
    Taxes: 12367,
    price: "264087",
    clientPrice: "282124",
    comission: "18037",
    pricebreakdown: [
      {
        BaseFare: "269757",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "6H 55Min",
      },
      {
        transit1: "1H 25Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "603",
          operatingcareer: "MH",
          operatingflight: "603",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T11:50:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T12:55:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 5Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "303",
          operatingcareer: "UL",
          operatingflight: "303",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:50:00",
          arrival: "CMB",
          arrivalTime: "2023-02-01T17:10:00",
          arrivalAirport: "Bandaranaike Intl Airport",
          arrivalLocation: "Colombo , LK",
          flightduration: "3H 50Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "225",
          operatingcareer: "UL",
          operatingflight: "225",
          departure: "CMB",
          departureAirport: "Bandaranaike Intl Airport",
          departureLocation: "Colombo , LK",
          departureTime: "2023-02-01T18:35:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T21:50:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "4H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "UL",
    careerName: "SriLankan Airlines",
    lastTicketTime: " ",
    BasePrice: 269757,
    Taxes: 12367,
    price: "264087",
    clientPrice: "282124",
    comission: "18037",
    pricebreakdown: [
      {
        BaseFare: "269757",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "10H 30Min",
      },
      {
        transit1: "1H 25Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "605",
          operatingcareer: "MH",
          operatingflight: "605",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T15:25:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T16:35:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "303",
          operatingcareer: "UL",
          operatingflight: "303",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:50:00",
          arrival: "CMB",
          arrivalTime: "2023-02-01T17:10:00",
          arrivalAirport: "Bandaranaike Intl Airport",
          arrivalLocation: "Colombo , LK",
          flightduration: "3H 50Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "225",
          operatingcareer: "UL",
          operatingflight: "225",
          departure: "CMB",
          departureAirport: "Bandaranaike Intl Airport",
          departureLocation: "Colombo , LK",
          departureTime: "2023-02-01T18:35:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T21:50:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "4H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "UL",
    careerName: "SriLankan Airlines",
    lastTicketTime: " ",
    BasePrice: 269757,
    Taxes: 12367,
    price: "264087",
    clientPrice: "282124",
    comission: "18037",
    pricebreakdown: [
      {
        BaseFare: "269757",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "4H 15Min",
      },
      {
        transit1: "1H 25Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "611",
          operatingcareer: "MH",
          operatingflight: "611",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T09:10:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T10:20:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "303",
          operatingcareer: "UL",
          operatingflight: "303",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:50:00",
          arrival: "CMB",
          arrivalTime: "2023-02-01T17:10:00",
          arrivalAirport: "Bandaranaike Intl Airport",
          arrivalLocation: "Colombo , LK",
          flightduration: "3H 50Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "225",
          operatingcareer: "UL",
          operatingflight: "225",
          departure: "CMB",
          departureAirport: "Bandaranaike Intl Airport",
          departureLocation: "Colombo , LK",
          departureTime: "2023-02-01T18:35:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T21:50:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "4H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "UL",
    careerName: "SriLankan Airlines",
    lastTicketTime: " ",
    BasePrice: 269757,
    Taxes: 12367,
    price: "264087",
    clientPrice: "282124",
    comission: "18037",
    pricebreakdown: [
      {
        BaseFare: "269757",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "9H 25Min",
      },
      {
        transit1: "1H 25Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "619",
          operatingcareer: "MH",
          operatingflight: "619",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T14:20:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T15:30:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "303",
          operatingcareer: "UL",
          operatingflight: "303",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:50:00",
          arrival: "CMB",
          arrivalTime: "2023-02-01T17:10:00",
          arrivalAirport: "Bandaranaike Intl Airport",
          arrivalLocation: "Colombo , LK",
          flightduration: "3H 50Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "225",
          operatingcareer: "UL",
          operatingflight: "225",
          departure: "CMB",
          departureAirport: "Bandaranaike Intl Airport",
          departureLocation: "Colombo , LK",
          departureTime: "2023-02-01T18:35:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T21:50:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "4H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "UL",
    careerName: "SriLankan Airlines",
    lastTicketTime: " ",
    BasePrice: 269757,
    Taxes: 12367,
    price: "264087",
    clientPrice: "282124",
    comission: "18037",
    pricebreakdown: [
      {
        BaseFare: "269757",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "5H 55Min",
      },
      {
        transit1: "1H 25Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "1",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "627",
          operatingcareer: "MH",
          operatingflight: "627",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T10:50:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T11:55:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 5Min",
          bookingcode: "J",
          seat: "1",
        },
      ],
      [
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "303",
          operatingcareer: "UL",
          operatingflight: "303",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T15:50:00",
          arrival: "CMB",
          arrivalTime: "2023-02-01T17:10:00",
          arrivalAirport: "Bandaranaike Intl Airport",
          arrivalLocation: "Colombo , LK",
          flightduration: "3H 50Min",
          bookingcode: "J",
          seat: "1",
        },
        {
          marketingcareer: "UL",
          marketingcareerName: "SriLankan Airlines",
          marketingflight: "225",
          operatingcareer: "UL",
          operatingflight: "225",
          departure: "CMB",
          departureAirport: "Bandaranaike Intl Airport",
          departureLocation: "Colombo , LK",
          departureTime: "2023-02-01T18:35:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T21:50:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "4H 45Min",
          bookingcode: "J",
          seat: "1",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 315916,
    Taxes: 12367,
    price: "307153",
    clientPrice: "328283",
    comission: "21130",
    pricebreakdown: [
      {
        BaseFare: "315916",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "6H 55Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "603",
          operatingcareer: "MH",
          operatingflight: "603",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T11:50:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T12:55:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 5Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 315916,
    Taxes: 12367,
    price: "307153",
    clientPrice: "328283",
    comission: "21130",
    pricebreakdown: [
      {
        BaseFare: "315916",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "5H 55Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "1",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "627",
          operatingcareer: "MH",
          operatingflight: "627",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T10:50:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T11:55:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 5Min",
          bookingcode: "J",
          seat: "1",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "1",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "J",
          seat: "1",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 315916,
    Taxes: 12367,
    price: "307153",
    clientPrice: "328283",
    comission: "21130",
    pricebreakdown: [
      {
        BaseFare: "315916",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "9H 25Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "619",
          operatingcareer: "MH",
          operatingflight: "619",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T14:20:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T15:30:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 315916,
    Taxes: 12367,
    price: "307153",
    clientPrice: "328283",
    comission: "21130",
    pricebreakdown: [
      {
        BaseFare: "315916",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "4H 15Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "611",
          operatingcareer: "MH",
          operatingflight: "611",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T09:10:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T10:20:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 315916,
    Taxes: 12367,
    price: "307153",
    clientPrice: "328283",
    comission: "21130",
    pricebreakdown: [
      {
        BaseFare: "315916",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "10H 30Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "605",
          operatingcareer: "MH",
          operatingflight: "605",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T15:25:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T16:35:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 315916,
    Taxes: 12367,
    price: "307153",
    clientPrice: "328283",
    comission: "21130",
    pricebreakdown: [
      {
        BaseFare: "315916",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "2H 55Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "197",
          operatingcareer: "MH",
          operatingflight: "197",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T22:55:00",
          arrival: "KUL",
          arrivalTime: "2023-01-02T04:55:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 0Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "601",
          operatingcareer: "MH",
          operatingflight: "601",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-02T07:50:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T09:05:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 15Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "2",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "J",
          seat: "2",
        },
      ],
    ],
  },
  {
    system: "Sabre",
    segment: "2",
    career: "BS",
    careerName: "USBangla Airlines",
    lastTicketTime: "2022-12-22 23:59",
    BasePrice: 315916,
    Taxes: 12367,
    price: "307153",
    clientPrice: "328283",
    comission: "21130",
    pricebreakdown: [
      {
        BaseFare: "315916",
        Tax: "12367",
        PaxCount: 1,
        PaxType: "ADT",
      },
    ],
    transit: [
      {
        transit1: "4H 40Min",
      },
      {
        transit1: "8H 50Min",
      },
    ],
    bags: [
      {
        adultBag: "40KG",
      },
      {
        adultBag: "40KG",
      },
    ],
    refundable: "Refundable",
    segments: [
      [
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "103",
          operatingcareer: "MH",
          operatingflight: "103",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-01-01T12:30:00",
          arrival: "KUL",
          arrivalTime: "2023-01-01T18:40:00",
          arrivalAirport: "Kuala Lumpur Intl Airport",
          arrivalLocation: "Kuala Lumpur , MY",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "5",
        },
        {
          marketingcareer: "MH",
          marketingcareerName: "Malaysia Airlines",
          marketingflight: "609",
          operatingcareer: "MH",
          operatingflight: "609",
          departure: "KUL",
          departureAirport: "Kuala Lumpur Intl Airport",
          departureLocation: "Dhaka , MY",
          departureTime: "2023-01-01T23:20:00",
          arrival: "SIN",
          arrivalTime: "2023-01-02T00:30:00",
          arrivalAirport: "Changi Intl Airport",
          arrivalLocation: "Singapore , SG",
          flightduration: "1H 10Min",
          bookingcode: "J",
          seat: "5",
        },
      ],
      [
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "308",
          operatingcareer: "BS",
          operatingflight: "308",
          departure: "SIN",
          departureAirport: "Changi Intl Airport",
          departureLocation: "Singapore , SG",
          departureTime: "2023-02-01T05:30:00",
          arrival: "DAC",
          arrivalTime: "2023-02-01T07:40:00",
          arrivalAirport: "Hazrat Shahjalal Intl Airport",
          arrivalLocation: "Dhaka , BD",
          flightduration: "4H 10Min",
          bookingcode: "J",
          seat: "5",
        },
        {
          marketingcareer: "BS",
          marketingcareerName: "USBangla Airlines",
          marketingflight: "341",
          operatingcareer: "BS",
          operatingflight: "341",
          departure: "DAC",
          departureAirport: "Hazrat Shahjalal Intl Airport",
          departureLocation: "Dhaka , BD",
          departureTime: "2023-02-01T16:30:00",
          arrival: "DXB",
          arrivalTime: "2023-02-01T20:15:00",
          arrivalAirport: "Dubai Intl Airport",
          arrivalLocation: "Dubai , AE",
          flightduration: "5H 45Min",
          bookingcode: "J",
          seat: "5",
        },
      ],
    ],
  },
];
